# Generated by Django 6.0.6 on 2026-08-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
