# Generated by Django 6.0.6 on 2026-08-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
