# Generated by Django 6.0.6 on 2026-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_course_part_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
