# Generated by Django 6.0.6 on 2026-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_course_resource_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='planned_minutes',
        ),
        migrations.AddField(
            model_name='task',
            name='resource_url',
            field=models.URLField(blank=True),
        ),
    ]
