# Generated by Django 6.0.6 on 2026-09-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_task_planned_minutes_task_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
