# Generated by Django 6.0.6 on 2026-09-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_dailytask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='actual_minutes',
            new_name='actual_seconds',
        ),
    ]
