# Generated by Django 6.0.6 on 2026-09-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_actual_minutes_dailytask_actual_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
