# Generated by Django 6.0.6 on 2026-07-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_is_active_auctionlisting_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='active',
        ),
    ]
